### PR TITLE
Debug by default

### PR DESCRIPTION
**Pull request by bergie**

### CODE REVIEW

**Comment by bergie** [comment]
@jonnor @trustmaster any qualms about merging and releasing this?

**Comment by trustmaster** [comment]
@bergie 2 concerns:

1. Some 3rd party packages just throw exceptions regardless of error handling convention they follow in the docs. E.g. `stripe` can suddenly throw an exception instead of returning `err` in callback in non-fatal situations such as CVC code being wrong. Would this mean a `process.exit(1)` from now on and `throw/catch` everywhere "just in case"?
2. How does one disable debug mode when embedding networks via ComponentLoader? Should be documented.

**Comment by bergie** [comment]
@trustmaster this at least makes the errors localized and easier to deal with than before for cases like Stripe. You can just do `network.on('process-error')` or even attach to the `error` event of an individual edge.

As for disabling it, run `network.setDebug(false)`.

**Comment by bergie** [comment]
The big issue this is solving is that errors thrown downstream would in the old setup percolate up the callback chain until they hit the first async component. And if that async component was a WirePattern with `forwardGroups`, it would fail to end the groups the job was in, causing subsequent jobs to be grouped wrongly.

**Comment by trustmaster** [comment]
I'm the first person it would make happy if it fixes the async exceptions popping up in random places across the graphs :+1: 

Just need to make sure all possible side effects are known and the feature is documented.

**Pull request merged**
