### PR TITLE
Switch component loading to fbp-manifest

### LINKED ISSUE #367: Split component discovery from component loading
Currently if NoFlo component cache is not enabled, we use the [read-installed](https://npmjs.org/package/read-installed) module to discover available components.

This should be separated from componentloader, and we should make "pre-heating" of available component list the default.

Related to #247 and to switching from component.io to NPM+WebPack on browser-side.

### PR DESCRIPTION
**Pull request by bergie**
This PR will migrate component discovery to be based on the [FBP Manifest](https://github.com/flowbased/fbp-manifest) instead of NPM traversal.

Will fix #367

Bonus items:

* Faster builds (30-40% faster on Travis)
* Should fix Windows builds, except for #408

### CODE REVIEW

**Comment by bergie** [comment]
@jonnor @trustmaster ready for review

**Comment by jonnor** [comment]
@bergie are we still reading from package.json / component.json if there is no fbp.json manifest file?

**Comment by jonnor** [comment]
Does this change anything for browser?

**Comment by jonnor** [comment]
Missing documentation on how one creates an fbp.json manifest for a project.
Also, are only apps required to have fbp.json manifests? Or should component libraries have them too?

**Comment by bergie** [comment]
@jonnor this doesn't affect browser builds so far. That is a separate project involving the migration away from component.io. Hence, for browser components the discovery works as it has.

For Node.js modules, adding components to `package.json` is no longer necessary, though `package.json` can still be used for registering a default icon, and for custom component loaders.

**Comment by bergie** [comment]
and now we're green also on Windows!

**Comment by jonnor** [comment]
If we require fbp.json and don't read from package.json this is a breaking change. This cannot be introduced in a patch version bump. At minimum needs to be 0.7.x, (if we followed semver this would be a major bump).

**Comment by jonnor** [comment]
The question about whether component libraries also need to generate `fbp.json` files is unanswered.

**Comment by bergie** [comment]
@jonnor this plus #409 would warrant going 0.7.0, agreed. However, the main difference with old behavior is that we don't need the `grunt-noflo-manifest` step for Node.js, since `fbp-manifest` discovery provides that functionality.

Component libraries _can_ provide their own `fbp.json` files, and down the line this will be a perf boost.

**Comment by jonnor** [comment]
@bergie should `grunt-noflo-manifest` generate a `fbp.json` file when `noflo` version is 0.7.x (or just always, since old noflo just won't care)? Then we don't need to change every single project that uses noflo, as most have grunt-noflo-manifest in there already...

**Comment by bergie** [comment]
@jonnor I'd rather deprecate the grunt tool as soon as we've gotten rid of component.io

**Comment by jonnor** [comment]
We're gonna need something just like grunt-noflo-manifest to integrate into the Gruntfile anyway. So why not spare the trouble of having to change one grunt task for another in each and every NoFlo project there is?

**Comment by bergie** [comment]
@jonnor well, that is anyway beside the point of this PR :-)

**Comment by jonnor** [comment]
Yes and no. This PR breaks every single project which uses NoFlo. A plan for unbreaking them is needed for this to be a responsible change, imo.

**Comment by bergie** [comment]
@jonnor this PR should not break a single NoFlo module.

**Comment by jonnor** [comment]
When there is no fbp.json file, how are components found on node.js then?

**Comment by bergie** [comment]
@jonnor the fbp-manifest `noflo` runtime support has a similar discovery mechanism as what grunt-noflo-manifest uses.

**Comment by jonnor** [comment]
@bergie That I understand. But how is that setup in all the existing projects? Practically no existing projects run fbp-manifest anywhere? Is there something I'm missing?

**Comment by bergie** [comment]
@jonnor ComponentLoader runs `fbp-manifest`'s list helper if cache is not found.

**Comment by jonnor** [comment]
Ok

**Pull request merged**
