### PR TITLE
Listcomponents error handling

### PR DESCRIPTION
**Pull request by bergie**
Expands on #407 by adding error handling to `listComponents`.

### CODE REVIEW

**Comment by bergie** [comment]
@jonnor ready for review

**Comment by jonnor** [comment]
Do we abort on first failure?
Is the `Error` object the original one caused by component failure?
Shouldn't the error contain the names of component(s) which failed? Or at least we print the stacktrace?

**Comment by bergie** [comment]
@jonnor `listComponents` errors are not caused by faulty components. Faulty components were already covered in the error handling improvements that landed in 0.6.

Instead, this is errors related to the project setup, like a corrupted `fbp.json` file.

**Comment by jonnor** [comment]
Ok

**Pull request merged**
